### ISSUE TITLE
Closing tags in HTML

### ISSUE THREAD

**Issue by aubreywullschleger** [testmysk1ll/prj-rev-bwfs-dasmoto#1]
Important for errors!  `<img>` elements are self-closing so you'll want to delete the closing `</img>` tags you have.  Here's more info about the syntax for `<img>` elements: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Examples

Example: https://github.com/testmysk1ll/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L11

**Comment by testmysk1ll** [comment]
My bad, thank you very much for picking up on this.
