### ISSUE TITLE
Locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [testmysk1ll/prj-rev-bwfs-dasmoto#3]
Simplify! Consider using locally stored images in your project as this is best practice for production code and will allow your page to load faster.  To do this you would create a new `images` folder inside your `resources` folder, like this:   
![screen shot 2018-01-20 at 7 12 39 pm](https://user-images.githubusercontent.com/11949479/35190418-f4ab3c8a-fe15-11e7-801a-039bf16f04d5.png)

Example: https://github.com/testmysk1ll/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L11

Then save the images you are using in your project to the new folder and use your `<img>` tags like this: `<img src="./resources/images/hacksaw.jpeg" alt="hacksaw paint brushes">`. Also, be sure to use descriptive `alt` attributes for your `<img>` elements (see above for example). This is best practice and helps make your site more accessible!

**Comment by testmysk1ll** [comment]
Note, thank you
