### ISSUE TITLE
Concise CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [testmysk1ll/prj-rev-bwfs-dasmoto#4]
Great!  Awesome job with your use of group selectors in your CSS!  This practice helps your CSS to be more concise.  Keep it up!

Example: https://github.com/testmysk1ll/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L1-L3

Do note that the `<strong>` element is typically using `font-weight: bold;` by default so you can feel free to delete the `strong` selector (and comma before it) on line 4.  See here for more info on the `<strong>` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong

**Comment by testmysk1ll** [comment]
Thank you, well noted.
