### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [testmysk1ll/prj-rev-bwfs-dasmoto#5]
Grade: Needs improvement 

Summary:
Great start to this project! I love your use group selectors for concise CSS.

A few things to work on here would be: 1. using correct syntax for self-closing elements, 2. using best practices for nesting and indentation in your HTML, and 3. using locally stored images with descriptive `alt` attributes for your `<img>` elements.

Next, after implementing my suggestions, I challenge you to research and implement media queries to make your page responsive for all screen widths.  Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by testmysk1ll** [comment]
Many thanks, all comments are well noted. Should I upload a new version where I implemented your suggestions?
